# Generated by Django 5.1.3 on 2024-11-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_address_supplier_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='gender',
            new_name='address',
        ),
    ]
